# Generated by Django 5.2.3 on 2025-06-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='caategory',
            new_name='category',
        ),
    ]
